spring:
  datasource:
    url: 'jdbc:h2:file:./usermanagement_db'
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: 'true'
      path: /h2
