name: ci

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ci:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run checkstyle
        uses: nikitasavinov/checkstyle-action@0.4.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter
          checkstyle_config: checkstyle.xml

      - name: Build Maven
        uses: qcastel/github-actions-maven/actions/maven@master
        with:
          maven-args: "jacocoTestReport"

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
#          min-coverage-changed-files: 60
#
#      - name: ReportGenerator
#        uses: danielpalme/ReportGenerator-GitHub-Action@4.8.6
#        if: always()
#        with:
#          reports: 'build/reports/jacoco/test/jacocoTestReport.xml'
#          targetdir: 'build/reports/ReportGenerator'
#          reporttypes: 'TextSummary'
#          verbosity: 'Warning'
#
#      - name: write PR Comment
#        uses: actions/github-script@v3
#        if: always()
#        with:
#          script: |
#            const fs = require('fs');
#            let text = fs.readFileSync("build/reports/ReportGenerator/Summary.txt", 'utf-8');
#            github.issues.createComment({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              body: text
#            })
